[project]
name = "nvgt.zip"
version = "0.1.0"
description = "A small website designed to help you download the latest version of the Nonvisual Gaming Toolkit."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "requests>=2.32.4",
]
